package com.vreader.app.data

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import com.vreader.app.search.SearchTextNormalizer
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner

/**
 * Feature #133 WI-1 — the book-scoped find-in-book (TXT/MD) surface added to [SearchDao] against an
 * in-memory v7 Room DB (real SQLite FTS4/unicode61 under Robolectric). Covers:
 *  - `matchingChunksPage`: all matching chunks in ONE book returned, other books excluded, cursor
 *    paging disjoint + ordered + gapless across pages, last page empty, `s.id = f.rowid` join shape.
 *  - `chunkAtOrAfter`: the round-3 resume path — an INCLUSIVE (`>=`) re-fetch of the CURRENT chunk so
 *    a partially-consumed chunk is not skipped by `matchingChunksPage`'s strict `>` bound.
 *  - `matchingChunkCount`: book-scoped count of matching chunks.
 *  - `observeIndexState`: a Flow that emits null (missing) then the row on insert.
 * Mirrors [SearchDaoTest]'s DB-build + FTS-mirror-insert idiom exactly (staging→copy→clear).
 */
@RunWith(RobolectricTestRunner::class)
class InBookSearchDaoTest {
    private lateinit var db: VReaderDatabase
    private lateinit var dao: SearchDao
    private val context: Context get() = ApplicationProvider.getApplicationContext()

    private fun keyFor(sha: Char, format: String = "txt") = "$format:${sha.toString().repeat(64)}:2048"
    private val bookA = keyFor('a')
    private val bookB = keyFor('b')

    @Before fun setUp() {
        db = Room.inMemoryDatabaseBuilder(context, VReaderDatabase::class.java)
            .allowMainThreadQueries().build()
        dao = db.searchDao()
    }

    @After fun tearDown() = db.close()

    private fun seedBook(key: String, format: String = "txt") = runBlocking {
        db.bookDao().upsert(
            BookEntity(
                fingerprintKey = key, title = "T", originalFormat = format,
                contentSHA256 = key.substringAfter(':').substringBefore(':'),
                fileByteCount = 2048L, localFilePath = null, sourceUri = null,
                addedAt = 1L, lastOpenedAt = null, author = null,
            ),
        )
    }

    /** Build + publish a section (id autogenerated); returns the persisted entity with its real id. */
    private fun publishSection(key: String, sectionIndex: Int, chunkOrdinal: Int, text: String): SearchSectionEntity =
        runBlocking {
            dao.insertStagingBatch(
                listOf(
                    SearchStagingEntity(
                        bookKey = key, sectionIndex = sectionIndex, chunkOrdinal = chunkOrdinal,
                        sectionTitle = null, text = text,
                        indexedText = SearchTextNormalizer.segmentCJK(SearchTextNormalizer.normalize(text)),
                    ),
                ),
            )
            dao.copyStagingToSections(key)
            dao.clearStaging(key)
            // The just-published chunk with this (sectionIndex, chunkOrdinal) — read back the real id.
            dao.sectionsFor(key).first { it.sectionIndex == sectionIndex && it.chunkOrdinal == chunkOrdinal }
        }

    private val firstCursor = Triple(-1, -1, -1L)

    private fun page(
        key: String, ftsQuery: String, cursor: Triple<Int, Int, Long> = firstCursor, limit: Int = 100,
    ) = runBlocking {
        dao.matchingChunksPage(key, ftsQuery, cursor.first, cursor.second, cursor.third, limit)
    }

    // ---- matchingChunksPage: book scoping + full result set ----

    @Test fun matchingChunksPage_returnsAllMatchingChunksInOneBook() = runBlocking {
        seedBook(bookA)
        publishSection(bookA, 0, 0, "alpha term appears here")
        publishSection(bookA, 1, 1, "another alpha in a later chunk")
        publishSection(bookA, 2, 2, "no keyword in this chunk")
        val hits = page(bookA, "alpha")
        assertEquals("both matching chunks returned", 2, hits.size)
        assertTrue("only matching chunks", hits.all { it.text.contains("alpha") })
    }

    @Test fun matchingChunksPage_excludesOtherBooks() = runBlocking {
        seedBook(bookA)
        seedBook(bookB)
        publishSection(bookA, 0, 0, "shared term in book A")
        publishSection(bookB, 0, 1, "shared term in book B")
        val hits = page(bookA, "shared")
        assertEquals("only book A's chunk", 1, hits.size)
        assertEquals("scoped to the requested book", bookA, hits.single().bookKey)
    }

    @Test fun matchingChunksPage_usesFtsRowidJoinShape() = runBlocking {
        // A content-table insert is only MATCHable via the FTS shadow if s.id = f.rowid. If the join
        // were s.rowid (wrong), the same-named alias would still work for a single row but the ordered
        // multi-book/multi-row cases below would misjoin. This asserts a straight FTS hit resolves.
        seedBook(bookA)
        publishSection(bookA, 0, 0, "the shadow join must resolve")
        val hits = page(bookA, "shadow")
        assertEquals("FTS shadow join (s.id = f.rowid) resolves the content row", 1, hits.size)
        assertTrue(hits.single().text.contains("shadow"))
    }

    // ---- cursor pagination: disjoint + ordered + gapless + empty last page ----

    @Test fun matchingChunksPage_cursorPaging_isOrderedDisjointGapless() = runBlocking {
        seedBook(bookA)
        // 5 matching chunks, inserted out of reading order to prove ORDER BY tuple governs, not insert order.
        publishSection(bookA, 4, 4, "widget five")
        publishSection(bookA, 0, 0, "widget one")
        publishSection(bookA, 3, 3, "widget four")
        publishSection(bookA, 1, 1, "widget two")
        publishSection(bookA, 2, 2, "widget three")

        val collected = mutableListOf<SearchSectionEntity>()
        var cursor = firstCursor
        while (true) {
            val batch = page(bookA, "widget", cursor, limit = 2)
            if (batch.isEmpty()) break
            collected += batch
            val last = batch.last()
            cursor = Triple(last.sectionIndex, last.chunkOrdinal, last.id)
        }
        // ordered by the (sectionIndex, chunkOrdinal, id) tuple
        assertEquals("all 5 chunks retrieved across pages", 5, collected.size)
        assertEquals(
            "reading-order tuple ascending",
            listOf(0, 1, 2, 3, 4), collected.map { it.sectionIndex },
        )
        // disjoint: no id appears twice
        assertEquals("no duplicate chunks across pages", collected.size, collected.map { it.id }.toSet().size)
    }

    @Test fun matchingChunksPage_lastPageIsEmpty() = runBlocking {
        seedBook(bookA)
        val only = publishSection(bookA, 0, 0, "solitary widget")
        val second = page(bookA, "widget", Triple(only.sectionIndex, only.chunkOrdinal, only.id), limit = 10)
        assertTrue("past the last chunk the page is empty", second.isEmpty())
    }

    // ---- chunkAtOrAfter: the round-3 INCLUSIVE resume path ----

    @Test fun chunkAtOrAfter_reFetchesCurrentChunk_whenCursorStillPointsIntoIt() = runBlocking {
        seedBook(bookA)
        val cur = publishSection(bookA, 1, 1, "resume target widget")
        publishSection(bookA, 2, 2, "next widget after")
        // Cursor STILL points at the current chunk (a partially-consumed chunk resumes here).
        val same = runBlocking {
            dao.chunkAtOrAfter(bookA, "widget", cur.sectionIndex, cur.chunkOrdinal, cur.id)
        }
        assertNotNull("chunkAtOrAfter re-fetches the current chunk inclusively", same)
        assertEquals("it is the SAME chunk, not skipped to the next", cur.id, same!!.id)
    }

    @Test fun chunkAtOrAfter_advancesToNext_whenCursorIsPastCurrent() = runBlocking {
        seedBook(bookA)
        val cur = publishSection(bookA, 1, 1, "consumed widget")
        val next = publishSection(bookA, 2, 2, "following widget")
        // Cursor id is PAST the current chunk's id (cur.id + 1) → the inclusive bound lands on the next.
        val after = runBlocking {
            dao.chunkAtOrAfter(bookA, "widget", cur.sectionIndex, cur.chunkOrdinal, cur.id + 1)
        }
        assertNotNull("a fully-consumed chunk advances to the next matching chunk", after)
        assertEquals("advanced to the next chunk", next.id, after!!.id)
    }

    @Test fun chunkAtOrAfter_returnsNull_whenNoMatchAtOrAfter() = runBlocking {
        seedBook(bookA)
        val only = publishSection(bookA, 0, 0, "final widget")
        val none = runBlocking {
            dao.chunkAtOrAfter(bookA, "widget", only.sectionIndex, only.chunkOrdinal, only.id + 1)
        }
        assertNull("no chunk at or after the last one", none)
    }

    // ---- matchingChunkCount ----

    @Test fun matchingChunkCount_countsMatchingChunksInBookOnly() = runBlocking {
        seedBook(bookA)
        seedBook(bookB)
        publishSection(bookA, 0, 0, "counter widget one")
        publishSection(bookA, 1, 1, "counter widget two")
        publishSection(bookA, 2, 2, "no match here")
        publishSection(bookB, 0, 3, "widget in the other book")
        assertEquals("two matching chunks in book A", 2, runBlocking { dao.matchingChunkCount(bookA, "widget") })
        assertEquals("one matching chunk in book B", 1, runBlocking { dao.matchingChunkCount(bookB, "widget") })
        assertEquals("no matches → 0", 0, runBlocking { dao.matchingChunkCount(bookA, "nonexistentterm") })
    }

    // ---- observeIndexState Flow ----

    @Test fun observeIndexState_emitsNullThenRowOnInsert() = runBlocking {
        seedBook(bookA)
        assertNull("no index-state row yet", dao.observeIndexState(bookA).first())
        dao.markIndexed(SearchIndexStateEntity(bookA, 1, 1L, "indexed"))
        val row = dao.observeIndexState(bookA).first()
        assertNotNull("row appears after markIndexed", row)
        assertEquals("the book's state row", "indexed", row!!.status)
        assertEquals("scoped to the requested book", bookA, row.bookKey)
    }
}
